[server]
headless = true
enableXsrfProtection = false
enableCORS = false
baseUrlPath = "dashboard"

[client]
showSidebarNavigation = false

[browser]
gatherUsageStats = false

[theme]
primaryColor="#870A30"
backgroundColor="#FFFFFF"
secondaryBackgroundColor="#ffebeb"
textColor="#31333F"
font="sans serif"
